# Simple linear regression

In [74]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression,Ridge,Lasso,LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer


In [2]:
df = pd.read_csv(r'C:\Users\vignesh\Desktop\work\Practice\salary.csv')
df.head()


YearsExperience  Salary
0              1.2   39344
1              1.4   46206
2              1.6   37732
3              2.1   43526
4              2.3   39892

In [39]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(["Salary"], axis=1), df["Salary"],test_size=0.22,random_state=42)

In [40]:
xtrain = x_train.to_numpy().reshape(len(x_train),1)
ytrain = y_train.to_numpy().reshape(len(y_train),1)
xtest = x_text.to_numpy().reshape(len(x_text),1)
ytest = y_test.to_numpy().reshape(len(y_test),1)

In [41]:
xtrain

array([[ 8.8],
       [ 4.1],
       [ 1.2],
       [ 2.3],
       [ 5.2],
       [ 3. ],
       [ 4.2],
       [ 4.1],
       [ 8. ],
       [ 1.4],
       [ 1.6],
       [ 9.1],
       [ 2.1],
       [ 7.2],
       [ 9.6],
       [ 6. ],
       [10.6],
       [ 6.9],
       [ 3.3],
       [ 4. ],
       [ 4.6],
       [ 6.1],
       [ 3.1]])

In [42]:
lin_reg=LinearRegression()

In [43]:
lin_reg.fit(xtrain,ytrain)

LinearRegression()

In [14]:
df

YearsExperience  Salary
0               1.2   39344
1               1.4   46206
2               1.6   37732
3               2.1   43526
4               2.3   39892
5               3.0   56643
6               3.1   60151
7               3.3   54446
8               3.3   64446
9               3.8   57190
10              4.0   63219
11              4.1   55795
12              4.1   56958
13              4.2   57082
14              4.6   61112
15              5.0   67939
16              5.2   66030
17              5.4   83089
18              6.0   81364
19              6.1   93941
20              6.9   91739
21              7.2   98274
22              8.0  101303
23              8.3  113813
24              8.8  109432
25              9.1  105583
26              9.6  116970
27              9.7  112636
28             10.4  122392
29             10.6  121873

In [44]:
lin_reg.predict(xtest)

array([[115790.43871147],
       [ 71499.1073352 ],
       [102597.27617386],
       [ 75268.58234595],
       [ 55478.83853953],
       [ 60190.68230297],
       [122387.01998028]])

In [45]:
xtest

array([[ 9.7],
       [ 5. ],
       [ 8.3],
       [ 5.4],
       [ 3.3],
       [ 3.8],
       [10.4]])

In [46]:
ytest

array([[112636],
       [ 67939],
       [113813],
       [ 83089],
       [ 64446],
       [ 57190],
       [122392]], dtype=int64)

In [47]:
lin_reg.score(xtest,ytest)

0.9317736970098528

#  Linear regression on boston data set

In [49]:
df = pd.read_csv(r'C:\Users\vignesh\Desktop\work\Practice\boston.csv')
df = df.drop('Unnamed: 0',axis = 1)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [50]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(["Price"], axis=1), df["Price"],test_size=0.22,random_state=42)

In [1]:
x_test

NameError: name 'x_test' is not defined

In [54]:
y_train

334    20.7
181    36.2
227    31.6
434    11.7
180    39.8
       ... 
106    19.5
270    21.1
348    24.5
435    13.4
102    18.6
Name: Price, Length: 394, dtype: float64

In [55]:
lin_reg=LinearRegression()

In [56]:
lin_reg.fit(x_train,y_train)

LinearRegression()

In [57]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  Price  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [59]:
lin_reg.predict(x_test)

array([28.97528729, 36.06237867, 14.78397171, 25.12703189, 18.70716381,
       23.17927344, 17.649153  , 14.26888579, 22.86584011, 20.64941593,
       24.87153295, 18.62998967, -6.31043237, 21.73416181, 19.2665216 ,
       26.08512913, 20.59744865,  5.70346772, 40.44438231, 17.55224901,
       27.3405011 , 30.08197623, 11.28417665, 24.20286806, 17.7861767 ,
       15.70779787, 22.82486833, 14.28009636, 22.38582343, 19.24801329,
       22.4194847 , 25.26690961, 25.81380051, 17.77194335, 16.56988316,
       17.06698769, 31.24491138, 20.23197429, 23.77401221, 24.6977688 ,
       13.96615136, 32.18687256, 42.58003453, 17.37629245, 27.29185258,
       16.9518109 , 14.03394078, 25.96666988, 20.17401538, 30.03614324,
       21.31030514, 34.35723372, 16.00971701, 26.21907939, 39.57339894,
       22.54577077, 18.80147753, 32.71609579, 25.09277568, 12.85514436,
       22.69197239, 30.48309917, 31.60069724, 15.97422868, 20.28853847,
       16.64940279, 20.42674664, 26.00856405, 30.65398295, 11.35

In [60]:
lin_reg.score(x_test,y_test)

0.671771096968799

In [62]:
ridge=Ridge()

In [63]:
ridge.fit(x_train,y_train)

Ridge()

In [64]:
ridge.predict(x_test)

array([28.68424495, 35.75654157, 14.12458301, 24.91381252, 19.03534379,
       22.3111814 , 17.58217165, 14.1398161 , 21.99455623, 20.79280674,
       24.14938871, 18.48676474, -6.53949034, 21.09007097, 19.23893663,
       25.9287557 , 20.20786066,  5.59652287, 40.37067195, 17.83399416,
       27.54497613, 29.95716842, 11.33470724, 24.65269255, 18.08502845,
       15.02980612, 22.27738211, 14.4806348 , 21.64444184, 19.48825361,
       21.99304346, 25.43555366, 25.81886287, 18.56743407, 15.84327233,
       18.37434291, 31.22071057, 20.79928258, 23.3061788 , 24.45926826,
       14.06165531, 32.09697073, 42.41815851, 17.08058745, 27.18899185,
       17.10925165, 14.09993363, 25.74352293, 19.63939403, 30.32315226,
       21.21122603, 34.18042188, 16.12932159, 26.28751755, 39.8435888 ,
       22.4163384 , 19.26018028, 32.79198806, 24.99966587, 12.60849132,
       23.04225234, 30.92946777, 31.7481623 , 16.46545363, 20.7224053 ,
       15.7593827 , 20.5166511 , 25.98763495, 30.88678502, 11.56

In [66]:
ridge.score(x_test,y_test)

0.6663274886484971

In [68]:
las=Lasso()
las.fit(x_train,y_train)

Lasso()

In [69]:
las.predict(x_test)

array([28.52460839, 32.29432791, 13.92475959, 25.6450593 , 18.87399874,
       22.07479557, 18.19720913, 12.23329679, 21.81937234, 21.17855167,
       21.4747247 , 20.34998783, -4.86227998, 20.96657778, 21.85521794,
       23.62575269, 20.53603035,  6.35435132, 36.76439768, 18.04638232,
       27.61032981, 29.04447057, 12.36769152, 24.50764011, 19.03718745,
       16.26198921, 23.05092104, 13.47151282, 19.5079024 , 20.60425296,
       23.0504064 , 26.27585819, 23.16793757, 23.06120151, 14.67957927,
       21.43341287, 30.85276237, 23.27532686, 20.78917864, 24.19855465,
       14.74421063, 30.79251968, 37.95244428, 18.98414055, 26.95557469,
       18.41843304, 15.84049587, 25.17951151, 19.0764519 , 31.24266441,
       23.57013062, 33.10676621, 16.53520214, 25.70639342, 37.38781787,
       22.49285015, 19.70352033, 31.96909484, 25.02197666, 15.34590064,
       24.02821287, 30.72061884, 31.0771937 , 18.81416015, 24.19919057,
       14.29135448, 19.5813313 , 26.59475541, 30.7206756 , 12.33

In [70]:
las.score(x_test,y_test)

0.6473088400475426